server:
  port: ${SERVER_PORT}
kafka:
  note.topic: ${KAFKA_TOPIC_NOTE}
  doctor.topic: ${KAFKA_TOPIC_DOCTOR}
  patient.topic: ${KAFKA_TOPIC_PATIENT}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
    producer:
      properties.spring.json.add.type.headers: false
data-service:
  base-url: ${DATA_SERVICE_BASE_URL}