server:
  port: ${SERVER_PORT}
spring:
  datasource.username: ${DB_USER}
  datasource.password: ${DB_PWD}
  datasource.url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  datasource.driverClassName: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
kafka:
  note.topic: ${KAFKA_TOPIC_NOTE}
  doctor.topic: ${KAFKA_TOPIC_DOCTOR}
  patient.topic: ${KAFKA_TOPIC_PATIENT}
  consumer.note.id: ${KAFKA_CONSUMER_NOTE_ID}
  consumer.doctor.id: ${KAFKA_CONSUMER_DOCTOR_ID}
  consumer.patient.id: ${KAFKA_CONSUMER_PATIENT_ID}
